const cfg=window.APP_CONFIG||{};
const configured=cfg.SUPABASE_URL?.startsWith('https://')&&!cfg.SUPABASE_URL.includes('PASTE_')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('PASTE_');
const sb=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const state={user:null,profile:null,settings:{store_name:'Shoes Store'},products:[],variants:[],sales:[],expenses:[],suppliers:[],purchases:[],customers:[],shifts:[],movements:[],returns:[],audit:[],cart:[],purchaseCart:[],charts:[],current:'dashboard'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const todayISO=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'}); const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=n=>Number(n||0); const dateId=d=>new Date(d).toLocaleString('id-ID',{timeZone:'Asia/Jakarta',dateStyle:'short',timeStyle:'short'});
function toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;$('#toast').appendChild(e);setTimeout(()=>e.remove(),3500)}
function metric(label,value,hint='',cls=''){return `<div class="card metric"><div class="label">${label}</div><div class="value ${cls}">${value}</div><div class="hint">${hint}</div></div>`}
async function audit(action,entity,id,details={}){try{await sb.rpc('write_audit',{p_action:action,p_entity:entity,p_entity_id:String(id||''),p_details:details})}catch{}}

async function init(){
 $('#connectionInfo').textContent=configured?'Database cloud siap. Login untuk memulai.':'Belum terhubung Supabase. Isi config.js terlebih dahulu.';
 $('#loginForm').addEventListener('submit',login);$('#logoutBtn').onclick=logout;$('#togglePassword').onclick=()=>{const p=$('#password');p.type=p.type==='password'?'text':'password'};$('#menuToggle').onclick=()=>$('#sidebar').classList.toggle('open');
 $('#saleDiscount').addEventListener('input',updateCheckout);$('#paymentMethod').addEventListener('change',updateCheckout);$('#paidAmount').addEventListener('input',updateCheckout);$('#confirmCheckout').onclick=checkout;$('#printReceipt').onclick=printReceiptOnly;$('#printBarcode').onclick=printBarcodeOnly;
 setInterval(()=>$('#clock')&&($('#clock').textContent=new Date().toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})),1000);
 if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('#installBtn').classList.add('hidden')}};
 if(!sb)return;const{data:{session}}=await sb.auth.getSession();if(session){state.user=session.user;await bootApp()}sb.auth.onAuthStateChange(async(e,s)=>{if(s&&!state.profile){state.user=s.user;await bootApp()}})
}
async function login(e){e.preventDefault();if(!sb)return toast('Hubungkan Supabase terlebih dahulu.');const{data,error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)return toast(error.message);state.user=data.user;await bootApp()}
async function logout(){if(sb)await sb.auth.signOut();location.reload()}
async function bootApp(){const{data,error}=await sb.from('profiles').select('*').eq('id',state.user.id).single();if(error||!data)return toast('Profil/role user belum dibuat di tabel profiles.');if(!data.active)return toast('Akun dinonaktifkan.');state.profile=data;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=data.full_name||state.user.email;$('#userRole').textContent=data.role.toUpperCase();buildNav();await refreshAll();subscribeRealtime();route('dashboard')}
function buildNav(){const role=state.profile.role;const all={kasir:[['UTAMA'],['dashboard','Dashboard'],['pos','Kasir / POS'],['shifts','Shift Kasir'],['sales','Riwayat Penjualan']],admin:[['UTAMA'],['dashboard','Dashboard'],['pos','Kasir / POS'],['products','Produk & Stok'],['purchases','Pembelian'],['suppliers','Supplier'],['stock','Stock Opname'],['returns','Retur'],['expenses','Pengeluaran'],['sales','Penjualan'],['reports','Laporan']],owner:[['UTAMA'],['dashboard','Dashboard Owner'],['pos','Kasir / POS'],['shifts','Shift Kasir'],['MASTER & STOK'],['products','Produk & Stok'],['suppliers','Supplier'],['purchases','Pembelian'],['stock','Stock Opname'],['returns','Retur'],['KEUANGAN'],['sales','Penjualan'],['expenses','Pengeluaran'],['reports','Laporan'],['KONTROL'],['audit','Audit Log'],['settings','Pengaturan']]}[role];$('#navMenu').innerHTML=all.map(x=>x.length===1?`<div class="nav-group">${x[0]}</div>`:`<button class="nav-btn" data-route="${x[0]}">${x[1]}</button>`).join('');$$('.nav-btn').forEach(b=>b.onclick=()=>route(b.dataset.route))}
function allowed(){return {kasir:['dashboard','pos','shifts','sales'],admin:['dashboard','pos','products','purchases','suppliers','stock','returns','expenses','sales','reports'],owner:['dashboard','pos','shifts','products','purchases','suppliers','stock','returns','expenses','sales','reports','audit','settings']}[state.profile.role]}
function route(name){if(!allowed().includes(name))return;state.current=name;$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===name));$('#sidebar').classList.remove('open');destroyCharts();({dashboard:renderDashboard,pos:renderPOS,products:renderProducts,suppliers:renderSuppliers,purchases:renderPurchases,stock:renderStock,returns:renderReturns,shifts:renderShifts,sales:renderSales,expenses:renderExpenses,reports:renderReports,audit:renderAudit,settings:renderSettings}[name]||renderDashboard)()}
function destroyCharts(){state.charts.forEach(c=>{try{c.destroy()}catch{}});state.charts=[]}
async function refreshAll(){
  const q=async(label,query,fallback)=>{
    try{const r=await query;if(r.error){console.error(label,r.error);if(label==='sales')toast('Gagal membaca data penjualan: '+(r.error.message||'cek RLS/database'));return fallback}return r.data??fallback}
    catch(e){console.error(label,e);return fallback}
  };
  state.settings=await q('settings',sb.from('settings').select('*').eq('id',1).maybeSingle(),state.settings);
  state.products=await q('products',sb.from('products').select('*,brands(name),categories(name)').order('name'),state.products);
  state.variants=await q('variants',sb.from('product_variants').select('*,products(name,sku,sale_price,cost_price,brand_id,category_id)').eq('active',true).order('size'),state.variants);

  // Jangan gunakan embedded profiles pada query sales. Jika relasi FK/permission
  // bermasalah, query sales tetap harus masuk agar omzet dan riwayat tidak menjadi Rp0.
  const sales=await q('sales',sb.from('sales').select('*').order('created_at',{ascending:false}).limit(500),state.sales);
  const cashierIds=[...new Set(sales.map(s=>s.cashier_id).filter(Boolean))];
  let profileMap={};
  if(cashierIds.length){
    const profs=await q('sales profiles',sb.from('profiles').select('id,full_name').in('id',cashierIds),[]);
    profileMap=Object.fromEntries(profs.map(p=>[p.id,p]));
  }
  state.sales=sales.map(s=>({...s,profiles:profileMap[s.cashier_id]||null}));

  state.expenses=await q('expenses',sb.from('expenses').select('*').order('expense_date',{ascending:false}).limit(500),state.expenses);
  state.customers=await q('customers',sb.from('customers').select('*').order('name'),state.customers);
  state.shifts=await q('shifts',sb.from('shifts').select('*').order('opened_at',{ascending:false}).limit(100),state.shifts);
  let i=0;
  if(state.profile.role!=='kasir'){
    state.suppliers=await q('suppliers',sb.from('suppliers').select('*').eq('active',true).order('name'),state.suppliers);
    state.purchases=await q('purchases',sb.from('purchases').select('*').order('created_at',{ascending:false}).limit(300),state.purchases);
    state.movements=await q('stock movements',sb.from('stock_movements').select('*,product_variants(size,color,products(name,sku))').order('created_at',{ascending:false}).limit(500),state.movements);
    state.returns=await q('returns',sb.from('sale_returns').select('*').order('created_at',{ascending:false}).limit(200),state.returns);
  }
  if(state.profile.role==='owner')state.audit=await q('audit',sb.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(500),state.audit);
  $('#storeNameSide').textContent=state.settings.store_name||'Shoes Store';
  $('#loginStoreName').textContent=state.settings.store_name||'Shoes Store';
}
function subscribeRealtime(){sb.channel('store-live-v2').on('postgres_changes',{event:'*',schema:'public',table:'sales'},reloadCurrent).on('postgres_changes',{event:'*',schema:'public',table:'product_variants'},reloadCurrent).on('postgres_changes',{event:'*',schema:'public',table:'expenses'},reloadCurrent).on('postgres_changes',{event:'*',schema:'public',table:'purchases'},reloadCurrent).on('postgres_changes',{event:'*',schema:'public',table:'shifts'},reloadCurrent).on('postgres_changes',{event:'*',schema:'public',table:'sale_returns'},reloadCurrent).subscribe()}
let reloadTimer;function reloadCurrent(){clearTimeout(reloadTimer);reloadTimer=setTimeout(async()=>{await refreshAll();route(state.current)},350)}

function completedSales(){return state.sales.filter(s=>['completed','partial_return'].includes(String(s.status||'').trim().toLowerCase()))}
function periodStats(days=30){const end=new Date(),start=new Date();start.setDate(end.getDate()-days+1);const sales=completedSales().filter(s=>new Date(s.created_at)>=start);const omzet=sales.reduce((a,s)=>a+num(s.net_total),0),hpp=sales.reduce((a,s)=>a+num(s.cogs_total),0),exp=state.expenses.filter(e=>new Date(e.expense_date)>=new Date(start.toISOString().slice(0,10))).reduce((a,e)=>a+num(e.amount),0);return{sales,omzet,hpp,gross:omzet-hpp,exp,net:omzet-hpp-exp}}
function renderDashboard(){const role=state.profile.role,today=todayISO(),todaySales=completedSales().filter(s=>new Date(s.created_at).toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'})===today),omzet=todaySales.reduce((a,s)=>a+num(s.net_total),0),hpp=todaySales.reduce((a,s)=>a+num(s.cogs_total),0),exp=state.expenses.filter(e=>e.expense_date===today).reduce((a,e)=>a+num(e.amount),0),stock=state.variants.reduce((a,v)=>a+num(v.stock_qty),0),low=state.variants.filter(v=>num(v.stock_qty)<=num(v.min_stock)).length,inventory=state.variants.reduce((a,v)=>a+num(v.stock_qty)*num(v.products?.cost_price),0),m=periodStats(30);$('#pageTitle').textContent=role==='owner'?'Dashboard Owner':role==='admin'?'Dashboard Admin':'Dashboard Kasir';$('#pageSubtitle').textContent='Data toko tersinkron realtime';let cards=role==='owner'?metric('Omzet Hari Ini',rupiah(omzet),'Transaksi selesai')+metric('Laba Kotor Hari Ini',rupiah(omzet-hpp),'Omzet - HPP')+metric('Laba Bersih Hari Ini',rupiah(omzet-hpp-exp),'Setelah pengeluaran',omzet-hpp-exp>=0?'kpi-good':'kpi-bad')+metric('Nilai Persediaan',rupiah(inventory),'Stok × harga modal'):role==='admin'?metric('Total Stok',stock+' pcs','Semua variasi')+metric('Stok Menipis',low+' variasi','Perlu perhatian')+metric('Penjualan Hari Ini',rupiah(omzet),'Realtime')+metric('Transaksi Hari Ini',todaySales.length,'Selesai'):metric('Penjualan Hari Ini',rupiah(omzet),'Realtime')+metric('Transaksi Saya',todaySales.filter(s=>s.cashier_id===state.user.id).length,'Hari ini')+metric('Barang Terjual',todaySales.reduce((a,s)=>a+num(s.item_count),0),'Hari ini')+metric('Stok Menipis',low+' variasi','Info stok');$('#content').innerHTML=`<div class="cards">${cards}</div>${role==='owner'?`<div class="grid2"><div class="card"><div class="section-title"><h3>Penjualan 14 Hari</h3></div><div class="chart-wrap"><canvas id="salesChart"></canvas></div></div><div class="card"><h3>Ringkasan 30 Hari</h3><div class="stat-list"><div class="stat-row"><span>Omzet</span><b>${rupiah(m.omzet)}</b></div><div class="stat-row"><span>HPP</span><b>${rupiah(m.hpp)}</b></div><div class="stat-row"><span>Laba Kotor</span><b>${rupiah(m.gross)}</b></div><div class="stat-row"><span>Pengeluaran</span><b>${rupiah(m.exp)}</b></div><div class="stat-row"><span>Laba Bersih</span><b>${rupiah(m.net)}</b></div><div class="stat-row"><span>Margin</span><b>${m.omzet?((m.net/m.omzet)*100).toFixed(1):0}%</b></div></div></div></div>`:''}<div class="grid2" style="margin-top:14px"><div class="card"><div class="section-title"><h3>Transaksi Terbaru</h3></div>${salesTable(state.sales.slice(0,8))}</div><div class="card"><div class="section-title"><h3>Stok Menipis</h3></div>${lowStockTable()}</div></div>`;if(role==='owner')drawSalesChart()}
function drawSalesChart(){const labels=[],vals=[];for(let i=13;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=d.toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});labels.push(d.toLocaleDateString('id-ID',{day:'2-digit',month:'short'}));vals.push(completedSales().filter(s=>new Date(s.created_at).toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'})===key).reduce((a,s)=>a+num(s.net_total),0))}state.charts.push(new Chart($('#salesChart'),{type:'line',data:{labels,datasets:[{label:'Omzet',data:vals,tension:.3,fill:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{callback:v=>'Rp'+new Intl.NumberFormat('id-ID',{notation:'compact'}).format(v)}}}}}))}
function lowStockTable(){const rows=state.variants.filter(v=>num(v.stock_qty)<=num(v.min_stock)).slice(0,12);return rows.length?`<div class="table-wrap"><table class="table"><tr><th>Produk</th><th>Size</th><th>Warna</th><th>Stok</th></tr>${rows.map(v=>`<tr><td>${esc(v.products?.name)}</td><td>${esc(v.size)}</td><td>${esc(v.color)}</td><td><span class="badge ${v.stock_qty===0?'bad':'warn'}">${v.stock_qty}</span></td></tr>`).join('')}</table></div>`:'<div class="empty">Stok aman.</div>'}

function renderPOS(){$('#pageTitle').textContent='Kasir / POS';$('#pageSubtitle').textContent='Cari nama, SKU atau scan barcode';$('#content').innerHTML=`<div class="pos-grid"><div class="card"><div class="toolbar"><input id="productSearch" autofocus placeholder="Cari / scan barcode..."><select id="posBrand"><option value="">Semua brand</option>${[...new Set(state.products.map(p=>p.brands?.name).filter(Boolean))].map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div id="productGrid" class="product-grid"></div></div><div class="card"><div class="section-title"><h3>Keranjang</h3><button id="clearCart" class="danger-btn compact">Kosongkan</button></div><div id="cartLines"></div><div class="cart-total"><span>Total</span><span id="cartTotal">Rp0</span></div><button id="payBtn" class="primary full">Bayar (F4)</button></div></div>`;$('#productSearch').oninput=renderProductGrid;$('#posBrand').onchange=renderProductGrid;$('#clearCart').onclick=()=>{state.cart=[];renderCart()};$('#payBtn').onclick=openCheckout;document.onkeydown=e=>{if(state.current!=='pos')return;if(e.key==='F4'){e.preventDefault();openCheckout()}if(e.key==='F2'){e.preventDefault();$('#productSearch').focus()}};renderProductGrid();renderCart();setTimeout(()=>$('#productSearch')?.focus(),30)}
function renderProductGrid(){const q=($('#productSearch')?.value||'').toLowerCase(),brand=$('#posBrand')?.value||'';const arr=state.variants.filter(v=>num(v.stock_qty)>0&&`${v.products?.name} ${v.products?.sku} ${v.barcode} ${v.size} ${v.color}`.toLowerCase().includes(q)&&(!brand||state.products.find(p=>p.id===v.product_id)?.brands?.name===brand));$('#productGrid').innerHTML=arr.slice(0,100).map(v=>`<div class="product-card" data-id="${v.id}"><strong>${esc(v.products?.name)}</strong><span>${esc(v.color)} • Size ${esc(v.size)} • Stok ${v.stock_qty}</span><strong>${rupiah(v.products?.sale_price)}</strong></div>`).join('')||'<div class="empty">Produk tidak ditemukan.</div>';$$('.product-card').forEach(e=>e.onclick=()=>addCart(e.dataset.id));if(q&&arr.length===1&&arr[0].barcode===q){addCart(arr[0].id);$('#productSearch').value='';renderProductGrid()}}
function addCart(id){const v=state.variants.find(x=>x.id===id);if(!v)return;const ex=state.cart.find(x=>x.variant_id===id);if(ex){if(ex.qty>=v.stock_qty)return toast('Stok tidak cukup');ex.qty++}else state.cart.push({variant_id:id,name:v.products.name,size:v.size,color:v.color,price:num(v.products.sale_price),cost:num(v.products.cost_price),qty:1,max:num(v.stock_qty),barcode:v.barcode});renderCart()}
function renderCart(){if(!$('#cartLines'))return;$('#cartLines').innerHTML=state.cart.length?state.cart.map((x,i)=>`<div class="cart-line"><div><strong>${esc(x.name)}</strong><small>${esc(x.color)} • Size ${esc(x.size)} • ${rupiah(x.price)}</small><div class="qty-tools"><button class="ghost" data-minus="${i}">−</button><b>${x.qty}</b><button class="ghost" data-plus="${i}">+</button></div></div><div><strong>${rupiah(x.qty*x.price)}</strong><br><button class="danger-btn compact" data-remove="${i}">Hapus</button></div></div>`).join(''):'<div class="empty">Keranjang masih kosong.</div>';$$('[data-minus]').forEach(b=>b.onclick=()=>{const x=state.cart[b.dataset.minus];x.qty--;if(x.qty<=0)state.cart.splice(b.dataset.minus,1);renderCart()});$$('[data-plus]').forEach(b=>b.onclick=()=>{const x=state.cart[b.dataset.plus];if(x.qty<x.max)x.qty++;else toast('Stok tidak cukup');renderCart()});$$('[data-remove]').forEach(b=>b.onclick=()=>{state.cart.splice(b.dataset.remove,1);renderCart()});$('#cartTotal').textContent=rupiah(cartGross())}
const cartGross=()=>state.cart.reduce((a,x)=>a+x.qty*x.price,0);function openCheckout(){if(!state.cart.length)return toast('Keranjang kosong');$('#saleDiscount').value=0;$('#paidAmount').value=cartGross();$('#checkoutDialog').showModal();updateCheckout()}
function updateCheckout(){const gross=cartGross(),disc=Math.min(num($('#saleDiscount')?.value),gross),net=gross-disc,method=$('#paymentMethod')?.value,paid=method==='Tunai'?num($('#paidAmount')?.value):net;if(method!=='Tunai'&&$('#paidAmount'))$('#paidAmount').value=net;$('#checkoutSummary').innerHTML=`${state.cart.length} baris • ${state.cart.reduce((a,x)=>a+x.qty,0)} item • Subtotal <b>${rupiah(gross)}</b>`;$('#checkoutNet').textContent=rupiah(net);$('#changeAmount').textContent=rupiah(Math.max(0,paid-net))}
async function checkout(){
  if(!state.cart.length)return toast('Keranjang kosong');
  const btn=$('#confirmCheckout');
  if(btn?.disabled)return;

  const gross=cartGross();
  const discount=Math.min(num($('#saleDiscount').value),gross);
  const net=gross-discount;
  const method=$('#paymentMethod').value;
  const paid=method==='Tunai'?num($('#paidAmount').value):net;

  if(paid<net)return toast('Uang dibayar kurang');
  if(state.profile.role==='kasir'&&discount>num(state.settings.cashier_max_discount))
    return toast('Diskon melebihi batas kasir');

  // Validasi cepat terhadap stok yang sedang tampil.
  for(const x of state.cart){
    const v=state.variants.find(row=>row.id===x.variant_id);
    if(!v)return toast(`Varian ${x.name} tidak ditemukan`);
    if(num(v.stock_qty)<x.qty)return toast(`Stok ${x.name} tidak cukup`);
  }

  if(btn)btn.disabled=true;
  try{
    const openShift=state.shifts.find(s=>s.cashier_id===state.user.id&&s.status==='open');
    const items=state.cart.map(x=>({variant_id:x.variant_id,qty:x.qty}));

    const {data:sale,error}=await sb.rpc('create_sale_transaction',{
      p_shift_id:openShift?.id||null,
      p_customer_id:null,
      p_discount_total:discount,
      p_payment_method:method,
      p_paid_amount:paid,
      p_items:items
    });

    let savedSale=sale;
    if(error){
      console.error('create_sale_transaction:',error);
      // Kompatibilitas dengan database lama yang belum memiliki RPC v2.5.
      // Transaksi tetap disimpan melalui tabel lama; trigger database menangani stok.
      if(error.code==='PGRST202'||/create_sale_transaction|function .* does not exist/i.test(error.message||'')){
        const {data:legacySale,error:legacyError}=await sb.from('sales').insert({
          cashier_id:state.user.id,shift_id:openShift?.id||null,customer_id:null,
          gross_total:gross,discount_total:discount,net_total:net,cogs_total:state.cart.reduce((a,x)=>a+x.qty*x.cost,0),
          payment_method:method,paid_amount:paid,change_amount:Math.max(0,paid-net),
          item_count:state.cart.reduce((a,x)=>a+x.qty,0),status:'completed'
        }).select().single();
        if(legacyError)return toast('Penjualan gagal disimpan: '+legacyError.message);
        const {error:itemError}=await sb.from('sale_items').insert(state.cart.map(x=>({
          sale_id:legacySale.id,variant_id:x.variant_id,qty:x.qty,unit_price:x.price,unit_cost:x.cost,subtotal:x.qty*x.price
        })));
        if(itemError){
          await sb.from('sales').update({status:'void',void_reason:'Gagal menyimpan item: '+itemError.message}).eq('id',legacySale.id);
          return toast('Item penjualan gagal disimpan: '+itemError.message);
        }
        savedSale=legacySale;
      }else return toast(error.message||'Transaksi gagal disimpan');
    }

    await audit('CREATE_SALE','sales',savedSale.id,{invoice:savedSale.invoice_no,total:savedSale.net_total});
    const saved=[...state.cart];
    state.cart=[];
    $('#checkoutDialog').close();
    toast('Transaksi berhasil tersimpan');
    showReceipt(savedSale,saved);
    await refreshAll();
    if(state.current==='pos')renderPOS();
  }catch(e){
    console.error(e);
    toast(e?.message||'Terjadi kesalahan saat menyimpan transaksi');
  }finally{
    if(btn)btn.disabled=false;
  }
}
function openPrintWindow(title,html,kind='receipt'){
  const w=window.open('','_blank','width=520,height=720');
  if(!w){toast('Popup diblokir browser. Izinkan pop-up untuk mencetak.');return}
  const isReceipt=kind==='receipt';
  const width=isReceipt?'76mm':'60mm';
  w.document.open();
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>
    *{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff;color:#000;font-family:Arial,Helvetica,sans-serif}
    body{padding:4mm;margin:0 auto;width:${width};font-size:12px;line-height:1.35}
    .receipt{text-align:center;width:100%}.receipt h3{font-size:17px;margin:0 0 4px}.receipt>small{display:block;margin-bottom:8px}
    .receipt-items{border-top:1px dashed #000;border-bottom:1px dashed #000;padding:8px 0;margin:8px 0;text-align:left}
    .receipt-row{display:flex;justify-content:space-between;gap:10px;text-align:left;margin:3px 0}.receipt-row span:last-child,.receipt-row b:last-child{text-align:right}
    .receipt p{margin:10px 0 0;text-align:center}.barcode-label{text-align:center;width:100%}.barcode-label svg,.barcode-label img{max-width:100%;height:auto}
    @page{margin:3mm} @media print{html,body{width:auto}body{padding:0;margin:0 auto}}
  </style></head><body>${html}<script>window.onload=()=>{setTimeout(()=>window.print(),150)};<\/script></body></html>`);
  w.document.close();
}
function printReceiptOnly(){
  const el=$('#receiptContent');
  if(!el||!el.innerHTML.trim())return toast('Struk belum tersedia');
  openPrintWindow('Struk Penjualan',el.innerHTML,'receipt');
}
function printBarcodeOnly(){
  const el=$('#barcodeContent');
  if(!el||!el.innerHTML.trim())return toast('Label barcode belum tersedia');
  openPrintWindow('Label Barcode',`<div class="barcode-label">${el.innerHTML}</div>`,'barcode');
}
function showReceipt(sale,items){const s=state.settings;$('#receiptContent').innerHTML=`<div class="receipt"><h3>${esc(s.store_name)}</h3><small>${esc(s.address||'')}<br>${esc(s.phone||'')}</small><div class="receipt-items"><small>${esc(sale.invoice_no)}<br>${dateId(sale.created_at)} • ${esc(state.profile.full_name)}</small>${items.map(x=>`<div style="margin-top:8px"><b>${esc(x.name)}</b><small><br>${esc(x.color)} / ${esc(x.size)}</small><div class="receipt-row"><span>${x.qty} × ${rupiah(x.price)}</span><span>${rupiah(x.qty*x.price)}</span></div></div>`).join('')}</div><div class="receipt-row"><span>Subtotal</span><b>${rupiah(sale.gross_total)}</b></div><div class="receipt-row"><span>Diskon</span><b>${rupiah(sale.discount_total)}</b></div><div class="receipt-row"><span>Total</span><b>${rupiah(sale.net_total)}</b></div><div class="receipt-row"><span>${esc(sale.payment_method)}</span><span>${rupiah(sale.paid_amount)}</span></div><div class="receipt-row"><span>Kembali</span><span>${rupiah(sale.change_amount)}</span></div><p><small>${esc(s.receipt_footer||'Terima kasih telah berbelanja.')}</small></p></div>`;$('#receiptDialog').showModal()}

function renderProducts(){$('#pageTitle').textContent='Produk & Stok';$('#pageSubtitle').textContent=state.profile.role==='owner'?'Owner dapat menambah, mengedit, mengarsipkan atau menghapus produk':'Master produk, varian ukuran/warna dan barcode';$('#content').innerHTML=`<div class="grid2"><div class="card"><h3>Tambah Produk</h3><div class="form-grid"><label>SKU<input id="pSku"></label><label>Nama Produk<input id="pName"></label><label>Brand<input id="pBrand" placeholder="Nike"></label><label>Kategori<input id="pCategory" placeholder="Running"></label><label>Harga Modal<input id="pCost" type="number"></label><label>Harga Jual<input id="pSale" type="number"></label><label>Ukuran<input id="pSize" placeholder="40"></label><label>Warna<input id="pColor" placeholder="Hitam"></label><label>Barcode<input id="pBarcode" placeholder="Opsional"></label><label>Stok Awal<input id="pStock" type="number" value="0"></label></div><button id="saveProduct" class="primary full">Simpan Produk & Varian</button></div><div class="card"><div class="section-title"><h3>Daftar Varian</h3><input id="stockSearch" placeholder="Cari produk..." style="max-width:220px"></div><div id="variantTable"></div></div></div>`;$('#saveProduct').onclick=saveProduct;$('#stockSearch').oninput=renderVariantTable;renderVariantTable()}
function renderVariantTable(){const q=($('#stockSearch')?.value||'').toLowerCase(),rows=state.variants.filter(v=>`${v.products?.name} ${v.products?.sku} ${v.size} ${v.color} ${v.barcode}`.toLowerCase().includes(q)),owner=state.profile.role==='owner';$('#variantTable').innerHTML=`<div class="table-wrap"><table class="table"><tr><th>Produk</th><th>Size</th><th>Warna</th><th>Stok</th><th>Modal</th><th>Jual</th><th>Barcode</th><th>Aksi</th></tr>${rows.map(v=>`<tr><td>${esc(v.products?.name)}<br><small>${esc(v.products?.sku)}</small></td><td>${esc(v.size)}</td><td>${esc(v.color)}</td><td><span class="badge ${v.stock_qty<=v.min_stock?'warn':'good'}">${v.stock_qty}</span></td><td>${owner?rupiah(v.products?.cost_price):'-'}</td><td>${rupiah(v.products?.sale_price)}</td><td>${esc(v.barcode||'-')}</td><td><div class="row-actions"><button class="ghost compact" data-barcode="${v.id}">Label</button>${owner?`<button class="ghost compact" data-edit-product="${v.id}">Edit</button><button class="danger-btn compact" data-delete-product="${v.product_id}">Hapus</button>`:''}</div></td></tr>`).join('')}</table></div>`;$$('[data-barcode]').forEach(b=>b.onclick=()=>showBarcode(b.dataset.barcode));$$('[data-edit-product]').forEach(b=>b.onclick=()=>openEditProduct(b.dataset.editProduct));$$('[data-delete-product]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.deleteProduct))}
function openEditProduct(variantId){if(state.profile.role!=='owner')return toast('Hanya Owner yang dapat mengedit produk');const v=state.variants.find(x=>x.id===variantId),p=state.products.find(x=>x.id===v?.product_id);if(!v||!p)return toast('Produk tidak ditemukan');$('#editProductId').value=p.id;$('#editVariantId').value=v.id;$('#eSku').value=p.sku||'';$('#eName').value=p.name||'';$('#eBrand').value=p.brands?.name||'';$('#eCategory').value=p.categories?.name||'';$('#eCost').value=num(p.cost_price);$('#eSale').value=num(p.sale_price);$('#eSize').value=v.size||'';$('#eColor').value=v.color||'';$('#eBarcode').value=v.barcode||'';$('#eMinStock').value=num(v.min_stock);$('#editProductDialog').showModal()}
async function saveProductEdit(){if(state.profile.role!=='owner')return toast('Hanya Owner yang dapat mengedit produk');const productId=$('#editProductId').value,variantId=$('#editVariantId').value,sku=$('#eSku').value.trim(),name=$('#eName').value.trim();if(!sku||!name)return toast('SKU dan nama produk wajib');async function master(table,name){if(!name)return null;let{data}=await sb.from(table).select('id').eq('name',name).maybeSingle();if(!data){const r=await sb.from(table).insert({name}).select('id').single();if(r.error)throw r.error;data=r.data}return data?.id}try{const brand_id=await master('brands',$('#eBrand').value.trim()),category_id=await master('categories',$('#eCategory').value.trim());const beforeP=state.products.find(x=>x.id===productId),beforeV=state.variants.find(x=>x.id===variantId);let r=await sb.from('products').update({sku,name,brand_id,category_id,cost_price:num($('#eCost').value),sale_price:num($('#eSale').value),updated_at:new Date().toISOString()}).eq('id',productId);if(r.error)return toast(r.error.message);r=await sb.from('product_variants').update({size:$('#eSize').value.trim()||'-',color:$('#eColor').value.trim()||'-',barcode:$('#eBarcode').value.trim()||null,min_stock:num($('#eMinStock').value)}).eq('id',variantId);if(r.error)return toast(r.error.message);await audit('UPDATE_PRODUCT','products',productId,{before:{sku:beforeP?.sku,name:beforeP?.name,cost_price:beforeP?.cost_price,sale_price:beforeP?.sale_price,size:beforeV?.size,color:beforeV?.color,barcode:beforeV?.barcode},after:{sku,name,cost_price:num($('#eCost').value),sale_price:num($('#eSale').value),size:$('#eSize').value,color:$('#eColor').value,barcode:$('#eBarcode').value}});$('#editProductDialog').close();toast('Produk berhasil diperbarui');await refreshAll();renderProducts()}catch(e){toast(e.message||'Gagal mengubah produk')}}
async function deleteProduct(productId){if(state.profile.role!=='owner')return toast('Hanya Owner yang dapat menghapus produk');const p=state.products.find(x=>x.id===productId);if(!p)return toast('Produk tidak ditemukan');if(!confirm(`Hapus produk “${p.name}”?\n\nJika produk sudah memiliki riwayat transaksi, produk akan diarsipkan agar laporan lama tetap aman.`))return;const variantIds=state.variants.filter(v=>v.product_id===productId).map(v=>v.id);let used=false;if(variantIds.length){const checks=await Promise.all([sb.from('sale_items').select('id',{count:'exact',head:true}).in('variant_id',variantIds),sb.from('purchase_items').select('id',{count:'exact',head:true}).in('variant_id',variantIds),sb.from('stock_movements').select('id',{count:'exact',head:true}).in('variant_id',variantIds)]);used=checks.some(x=>(x.count||0)>0)}if(used){let r=await sb.from('product_variants').update({active:false}).eq('product_id',productId);if(r.error)return toast(r.error.message);r=await sb.from('products').update({active:false,updated_at:new Date().toISOString()}).eq('id',productId);if(r.error)return toast(r.error.message);await audit('ARCHIVE_PRODUCT','products',productId,{name:p.name,reason:'Produk memiliki riwayat transaksi'});toast('Produk memiliki riwayat transaksi, sehingga diarsipkan (tidak tampil di POS)')}else{const r=await sb.from('products').delete().eq('id',productId);if(r.error){return toast('Produk tidak dapat dihapus permanen: '+r.error.message)}await audit('DELETE_PRODUCT','products',productId,{name:p.name,sku:p.sku});toast('Produk berhasil dihapus permanen')}await refreshAll();renderProducts()}
async function saveProduct(){const sku=$('#pSku').value.trim(),name=$('#pName').value.trim();if(!sku||!name)return toast('SKU dan nama wajib');async function master(table,name){if(!name)return null;let{data}=await sb.from(table).select('id').eq('name',name).maybeSingle();if(!data){const r=await sb.from(table).insert({name}).select('id').single();data=r.data}return data?.id}const brand_id=await master('brands',$('#pBrand').value.trim()),category_id=await master('categories',$('#pCategory').value.trim());const{data:p,error}=await sb.from('products').insert({sku,name,brand_id,category_id,cost_price:num($('#pCost').value),sale_price:num($('#pSale').value)}).select().single();if(error)return toast(error.message);const vr=await sb.from('product_variants').insert({product_id:p.id,size:$('#pSize').value||'-',color:$('#pColor').value||'-',barcode:$('#pBarcode').value||null,stock_qty:num($('#pStock').value),min_stock:num(state.settings.default_min_stock||3)});if(vr.error)return toast(vr.error.message);await audit('CREATE_PRODUCT','products',p.id,{sku,name});toast('Produk tersimpan');await refreshAll();renderProducts()}
function showBarcode(id){const v=state.variants.find(x=>x.id===id);if(!v)return;$('#barcodeContent').innerHTML=`<b>${esc(v.products.name)}</b><div>${esc(v.color)} • Size ${esc(v.size)}</div><svg id="barcodeSvg"></svg><b>${rupiah(v.products.sale_price)}</b>`;JsBarcode('#barcodeSvg',v.barcode||v.products.sku,{format:'CODE128',displayValue:true,height:55,margin:8});$('#barcodeDialog').showModal()}

function renderSuppliers(){
 const owner=state.profile.role==='owner';
 $('#pageTitle').textContent='Supplier';
 $('#pageSubtitle').textContent=owner?'Owner dapat menambah, mengedit, mengarsipkan atau menghapus supplier':'Master pemasok barang';
 $('#content').innerHTML=`<div class="grid2"><div class="card"><h3>Tambah Supplier</h3><div class="form-grid"><label>Nama<input id="sName"></label><label>Telepon<input id="sPhone"></label><label>WhatsApp<input id="sWa"></label><label>Email<input id="sEmail"></label><label>Kontak Person<input id="sContact"></label><label class="span2">Alamat<textarea id="sAddress"></textarea></label><label class="span2">Catatan<textarea id="sNotes"></textarea></label></div><button id="saveSupplier" class="primary full">Simpan Supplier</button></div><div class="card"><h3>Daftar Supplier</h3><div class="table-wrap"><table class="table"><tr><th>Nama</th><th>Telepon</th><th>WhatsApp</th><th>Kontak</th><th>Alamat</th>${owner?'<th>Aksi</th>':''}</tr>${state.suppliers.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.phone||'-')}</td><td>${esc(s.whatsapp||'-')}</td><td>${esc(s.contact_person||'-')}</td><td>${esc(s.address||'-')}</td>${owner?`<td><div class="row-actions"><button class="ghost compact" data-edit-supplier="${s.id}">Edit</button><button class="danger-btn compact" data-delete-supplier="${s.id}">Hapus</button></div></td>`:''}</tr>`).join('')}</table></div></div></div>
 <dialog id="editSupplierDialog"><div class="dialog-card"><div class="dialog-head"><h3>Edit Supplier</h3><button class="icon-btn" id="closeSupplierEdit">✕</button></div><input id="editSupplierId" type="hidden"><div class="form-grid"><label>Nama<input id="esName"></label><label>Telepon<input id="esPhone"></label><label>WhatsApp<input id="esWa"></label><label>Email<input id="esEmail"></label><label>Kontak Person<input id="esContact"></label><label class="span2">Alamat<textarea id="esAddress"></textarea></label><label class="span2">Catatan<textarea id="esNotes"></textarea></label></div><button id="saveSupplierEdit" class="primary full">Simpan Perubahan</button></div></dialog>`;
 $('#saveSupplier').onclick=saveSupplier;
 if(owner){
  $$('[data-edit-supplier]').forEach(b=>b.onclick=()=>openEditSupplier(b.dataset.editSupplier));
  $$('[data-delete-supplier]').forEach(b=>b.onclick=()=>deleteSupplier(b.dataset.deleteSupplier));
  $('#closeSupplierEdit').onclick=()=>$('#editSupplierDialog').close();
  $('#saveSupplierEdit').onclick=saveSupplierEdit;
 }
}
async function saveSupplier(){if(!$('#sName').value.trim())return toast('Nama supplier wajib');const payload={name:$('#sName').value.trim(),phone:$('#sPhone').value,whatsapp:$('#sWa').value,email:$('#sEmail').value,contact_person:$('#sContact').value,address:$('#sAddress').value,notes:$('#sNotes').value,active:true};const{data,error}=await sb.from('suppliers').insert(payload).select().single();if(error)return toast(error.message);await audit('CREATE_SUPPLIER','suppliers',data.id,{name:payload.name});toast('Supplier ditambahkan');await refreshAll();renderSuppliers()}
function openEditSupplier(id){if(state.profile.role!=='owner')return toast('Hanya Owner yang dapat mengedit supplier');const s=state.suppliers.find(x=>x.id===id);if(!s)return toast('Supplier tidak ditemukan');$('#editSupplierId').value=s.id;$('#esName').value=s.name||'';$('#esPhone').value=s.phone||'';$('#esWa').value=s.whatsapp||'';$('#esEmail').value=s.email||'';$('#esContact').value=s.contact_person||'';$('#esAddress').value=s.address||'';$('#esNotes').value=s.notes||'';$('#editSupplierDialog').showModal()}
async function saveSupplierEdit(){if(state.profile.role!=='owner')return toast('Hanya Owner yang dapat mengedit supplier');const id=$('#editSupplierId').value,name=$('#esName').value.trim();if(!name)return toast('Nama supplier wajib');const before=state.suppliers.find(x=>x.id===id);const payload={name,phone:$('#esPhone').value,whatsapp:$('#esWa').value,email:$('#esEmail').value,contact_person:$('#esContact').value,address:$('#esAddress').value,notes:$('#esNotes').value};const{error}=await sb.from('suppliers').update(payload).eq('id',id);if(error)return toast(error.message);await audit('UPDATE_SUPPLIER','suppliers',id,{before:{name:before?.name,phone:before?.phone,whatsapp:before?.whatsapp,email:before?.email},after:payload});$('#editSupplierDialog').close();toast('Supplier berhasil diperbarui');await refreshAll();renderSuppliers()}
async function deleteSupplier(id){if(state.profile.role!=='owner')return toast('Hanya Owner yang dapat menghapus supplier');const s=state.suppliers.find(x=>x.id===id);if(!s)return toast('Supplier tidak ditemukan');if(!confirm(`Hapus supplier “${s.name}”?\n\nJika supplier sudah memiliki riwayat pembelian, supplier akan diarsipkan agar histori pembelian tetap aman.`))return;const{count,error:ce}=await sb.from('purchases').select('id',{count:'exact',head:true}).eq('supplier_id',id);if(ce)return toast(ce.message);if((count||0)>0){const{error}=await sb.from('suppliers').update({active:false}).eq('id',id);if(error)return toast(error.message);await audit('ARCHIVE_SUPPLIER','suppliers',id,{name:s.name,purchase_count:count});toast('Supplier memiliki riwayat pembelian, sehingga diarsipkan')}else{const{error}=await sb.from('suppliers').delete().eq('id',id);if(error)return toast('Supplier tidak dapat dihapus: '+error.message);await audit('DELETE_SUPPLIER','suppliers',id,{name:s.name});toast('Supplier berhasil dihapus permanen')}await refreshAll();renderSuppliers()}

function renderPurchases(){
 $('#pageTitle').textContent='Pembelian Barang';
 $('#pageSubtitle').textContent='Barang diterima akan menambah stok dan memperbarui average cost';
 $('#content').innerHTML=`<div class="grid2"><div class="card"><h3>Buat Pembelian</h3><div class="form-grid"><label>Supplier<select id="buySupplier"><option value="">Pilih Supplier</option>${state.suppliers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label>Tanggal<input id="buyDate" type="date" value="${todayISO()}"></label><label class="span2">Cari Varian<input id="buyVariantSearch" type="search" placeholder="Ketik nama, SKU, barcode, ukuran, atau warna..." autocomplete="off"></label><label class="span2">Pilih Varian<select id="buyVariant"><option value="">Pilih produk / size / warna</option></select><small class="help-text" id="buyVariantCount"></small></label><label>Qty<input id="buyQty" type="number" min="1" value="1"></label><label>Harga Beli / pcs<input id="buyCost" type="number" min="0"></label></div><button id="addBuy" class="ghost full">Tambah Item</button><div id="purchaseCart"></div><div class="cart-total"><span>Total</span><span id="purchaseTotal">Rp0</span></div><button id="savePurchase" class="primary full">Simpan & Tambah Stok</button></div><div class="card"><h3>Riwayat Pembelian</h3><div class="table-wrap"><table class="table"><tr><th>No.</th><th>Tanggal</th><th>Supplier</th><th>Total</th></tr>${state.purchases.map(p=>`<tr><td>${esc(p.purchase_no)}</td><td>${p.purchase_date}</td><td>${esc(p.suppliers?.name||'-')}</td><td>${rupiah(p.total)}</td></tr>`).join('')}</table></div></div></div>`;
 $('#addBuy').onclick=addPurchaseItem;
 $('#savePurchase').onclick=savePurchase;
 $('#buyVariantSearch').oninput=filterPurchaseVariants;
 $('#buyVariant').onchange=()=>{
   const v=state.variants.find(x=>x.id===$('#buyVariant').value);
   if(v && !num($('#buyCost').value)) $('#buyCost').value=num(v.products?.cost_price)||'';
 };
 filterPurchaseVariants();
 renderPurchaseCart();
}
function filterPurchaseVariants(){
 const sel=$('#buyVariant'); if(!sel)return;
 const q=($('#buyVariantSearch')?.value||'').trim().toLowerCase();
 const current=sel.value;
 const arr=state.variants.filter(v=>`${v.products?.name||''} ${v.products?.sku||''} ${v.barcode||''} ${v.size||''} ${v.color||''}`.toLowerCase().includes(q));
 sel.innerHTML=`<option value="">${arr.length?'Pilih produk / size / warna':'Varian tidak ditemukan'}</option>`+arr.slice(0,300).map(v=>`<option value="${v.id}">${esc(v.products?.sku||'-')} • ${esc(v.products?.name||'-')} • Size ${esc(v.size)} • ${esc(v.color)} • Stok ${num(v.stock_qty)}</option>`).join('');
 if(arr.some(v=>v.id===current))sel.value=current;
 const c=$('#buyVariantCount');if(c)c.textContent=q?`${arr.length} varian ditemukan`:`${arr.length} varian tersedia`;
}
function addPurchaseItem(){const id=$('#buyVariant').value,v=state.variants.find(x=>x.id===id),qty=num($('#buyQty').value),cost=num($('#buyCost').value);if(!v||qty<=0||cost<=0)return toast('Pilih varian, qty dan harga beli');state.purchaseCart.push({variant_id:id,name:v.products.name,size:v.size,color:v.color,qty,unit_cost:cost});renderPurchaseCart()}
function renderPurchaseCart(){if(!$('#purchaseCart'))return;$('#purchaseCart').innerHTML=state.purchaseCart.map((x,i)=>`<div class="purchase-line"><div><b>${esc(x.name)}</b><small> ${esc(x.color)} / ${esc(x.size)}</small></div><div>${x.qty} × ${rupiah(x.unit_cost)} <button class="danger-btn compact" data-rbuy="${i}">x</button></div></div>`).join('')||'<div class="empty">Belum ada item.</div>';$$('[data-rbuy]').forEach(b=>b.onclick=()=>{state.purchaseCart.splice(b.dataset.rbuy,1);renderPurchaseCart()});$('#purchaseTotal').textContent=rupiah(state.purchaseCart.reduce((a,x)=>a+x.qty*x.unit_cost,0))}
async function savePurchase(){if(!$('#buySupplier').value||!state.purchaseCart.length)return toast('Pilih supplier dan item');const total=state.purchaseCart.reduce((a,x)=>a+x.qty*x.unit_cost,0);const{data:p,error}=await sb.from('purchases').insert({supplier_id:$('#buySupplier').value,purchase_date:$('#buyDate').value,subtotal:total,total,created_by:state.user.id,status:'received'}).select().single();if(error)return toast(error.message);const{error:ie}=await sb.from('purchase_items').insert(state.purchaseCart.map(x=>({purchase_id:p.id,variant_id:x.variant_id,qty:x.qty,unit_cost:x.unit_cost,subtotal:x.qty*x.unit_cost})));if(ie)return toast(ie.message);await audit('CREATE_PURCHASE','purchases',p.id,{total});state.purchaseCart=[];toast('Pembelian tersimpan, stok bertambah');await refreshAll();renderPurchases()}

function renderStock(){ $('#pageTitle').textContent='Stock Opname & Kartu Stok';$('#pageSubtitle').textContent='Penyesuaian stok fisik dengan audit trail';$('#content').innerHTML=`<div class="grid2"><div class="card"><h3>Stock Opname</h3><div class="form-grid"><label class="span2">Varian<select id="opVariant"><option value="">Pilih produk</option>${state.variants.map(v=>`<option value="${v.id}">${esc(v.products.name)} • ${esc(v.size)} • ${esc(v.color)} • Sistem ${v.stock_qty}</option>`).join('')}</select></label><label>Stok Fisik<input id="physicalQty" type="number" min="0"></label><label>Alasan<input id="opReason" placeholder="Selisih opname"></label></div><button id="saveOpname" class="primary full">Simpan Penyesuaian</button></div><div class="card"><h3>Kartu Stok Terbaru</h3><div class="table-wrap"><table class="table"><tr><th>Waktu</th><th>Produk</th><th>Jenis</th><th>Perubahan</th><th>Saldo</th></tr>${state.movements.slice(0,100).map(m=>`<tr><td>${dateId(m.created_at)}</td><td>${esc(m.product_variants?.products?.name)} ${esc(m.product_variants?.size)}/${esc(m.product_variants?.color)}</td><td>${esc(m.movement_type)}</td><td>${m.qty_change>0?'+':''}${m.qty_change}</td><td>${m.balance_after??'-'}</td></tr>`).join('')}</table></div></div></div>`;$('#saveOpname').onclick=saveOpname}
async function saveOpname(){const v=state.variants.find(x=>x.id===$('#opVariant').value),physical=num($('#physicalQty').value);if(!v||physical<0)return toast('Pilih varian dan stok fisik');const{data:o,error}=await sb.from('stock_opnames').insert({opname_date:todayISO(),created_by:state.user.id,notes:$('#opReason').value}).select().single();if(error)return toast(error.message);const diff=physical-num(v.stock_qty);const r=await sb.from('stock_opname_items').insert({opname_id:o.id,variant_id:v.id,system_qty:v.stock_qty,physical_qty:physical,difference:diff,reason:$('#opReason').value});if(r.error)return toast(r.error.message);await audit('STOCK_OPNAME','stock_opnames',o.id,{product:v.products.name,system:v.stock_qty,physical,diff});toast('Stock opname tersimpan');await refreshAll();renderStock()}

function renderReturns(){ $('#pageTitle').textContent='Retur';$('#pageSubtitle').textContent='Retur penjualan dan retur supplier';$('#content').innerHTML=`<div class="grid2"><div class="card"><h3>Retur Penjualan</h3><div class="notice">Masukkan invoice, lalu pilih item. Barang kondisi baik dapat dikembalikan ke stok.</div><div class="form-grid"><label class="span2">Invoice<input id="retInvoice" placeholder="INV-..."></label><label>Qty<input id="retQty" type="number" min="1" value="1"></label><label>Alasan<input id="retReason" placeholder="Tukar size / cacat"></label><label>Kembalikan ke stok?<select id="retRestock"><option value="true">Ya</option><option value="false">Tidak</option></select></label><label>Refund<input id="retRefund" type="number" value="0"></label></div><button id="findSale" class="ghost full">Cari Invoice & Buat Retur</button></div><div class="card"><h3>Riwayat Retur</h3><div class="table-wrap"><table class="table"><tr><th>No.</th><th>Tanggal</th><th>Alasan</th><th>Refund</th></tr>${state.returns.map(r=>`<tr><td>${esc(r.return_no)}</td><td>${r.return_date}</td><td>${esc(r.reason||'-')}</td><td>${rupiah(r.refund_amount)}</td></tr>`).join('')}</table></div></div></div>`;$('#findSale').onclick=createReturn}
async function createReturn(){const invoice=$('#retInvoice').value.trim();if(!invoice)return toast('Masukkan invoice');const{data:sale,error}=await sb.from('sales').select('*,sale_items(*)').eq('invoice_no',invoice).maybeSingle();if(error||!sale)return toast('Invoice tidak ditemukan');if(!sale.sale_items?.length)return toast('Item transaksi tidak ditemukan');const item=sale.sale_items[0],qty=Math.min(num($('#retQty').value),item.qty);const{data:r,error:re}=await sb.from('sale_returns').insert({sale_id:sale.id,return_date:todayISO(),return_type:'refund',refund_amount:num($('#retRefund').value),reason:$('#retReason').value,created_by:state.user.id}).select().single();if(re)return toast(re.message);const ir=await sb.from('sale_return_items').insert({return_id:r.id,sale_item_id:item.id,variant_id:item.variant_id,qty,amount:num($('#retRefund').value),restock:$('#retRestock').value==='true'});if(ir.error)return toast(ir.error.message);await sb.from('sales').update({status:qty>=item.qty?'returned':'partial_return'}).eq('id',sale.id);await audit('SALE_RETURN','sale_returns',r.id,{invoice,qty});toast('Retur berhasil dicatat');await refreshAll();renderReturns()}

function renderShifts(){const open=state.shifts.find(s=>s.cashier_id===state.user.id&&s.status==='open');$('#pageTitle').textContent='Shift Kasir';$('#pageSubtitle').textContent='Buka/tutup kas dan pantau selisih';let expected=0;if(open){expected=num(open.opening_cash)+completedSales().filter(s=>s.shift_id===open.id&&s.payment_method==='Tunai').reduce((a,s)=>a+num(s.net_total)-num(s.change_amount),0)}$('#content').innerHTML=`<div class="grid2"><div class="card"><h3>${open?'Shift Sedang Aktif':'Buka Shift'}</h3>${open?`<div class="stat-list"><div class="stat-row"><span>Dibuka</span><b>${dateId(open.opened_at)}</b></div><div class="stat-row"><span>Kas Awal</span><b>${rupiah(open.opening_cash)}</b></div><div class="stat-row"><span>Kas Seharusnya</span><b>${rupiah(expected)}</b></div></div><div class="form-grid"><label class="span2">Kas Aktual<input id="actualCash" type="number" value="${expected}"></label></div><button id="closeShift" class="primary full">Tutup Shift</button>`:`<div class="form-grid"><label class="span2">Modal Kas Awal<input id="openingCash" type="number" value="0"></label></div><button id="openShift" class="primary full">Buka Shift</button>`}</div><div class="card"><h3>Riwayat Shift</h3><div class="table-wrap"><table class="table"><tr><th>Kasir</th><th>Buka</th><th>Tutup</th><th>Selisih</th></tr>${state.shifts.slice(0,30).map(s=>`<tr><td>${esc(s.profiles?.full_name)}</td><td>${dateId(s.opened_at)}</td><td>${s.closed_at?dateId(s.closed_at):'<span class="badge good">Aktif</span>'}</td><td>${s.difference==null?'-':rupiah(s.difference)}</td></tr>`).join('')}</table></div></div></div>`;if(open)$('#closeShift').onclick=()=>closeShift(open,expected);else $('#openShift').onclick=openShift}
async function openShift(){const{error}=await sb.from('shifts').insert({cashier_id:state.user.id,opening_cash:num($('#openingCash').value)});if(error)return toast(error.message);await audit('OPEN_SHIFT','shifts','',{opening:num($('#openingCash').value)});toast('Shift dibuka');await refreshAll();renderShifts()}
async function closeShift(open,expected){const actual=num($('#actualCash').value),diff=actual-expected;const{error}=await sb.from('shifts').update({closed_at:new Date().toISOString(),actual_cash:actual,expected_cash:expected,difference:diff,status:'closed'}).eq('id',open.id);if(error)return toast(error.message);await audit('CLOSE_SHIFT','shifts',open.id,{expected,actual,diff});toast('Shift ditutup');await refreshAll();renderShifts()}

function salesTable(rows){return `<div class="table-wrap"><table class="table"><tr><th>Invoice</th><th>Waktu</th><th>Kasir</th><th>Metode</th><th>Total</th><th>Status</th></tr>${rows.map(s=>`<tr><td>${esc(s.invoice_no)}</td><td>${dateId(s.created_at)}</td><td>${esc(s.profiles?.full_name||'-')}</td><td>${esc(s.payment_method)}</td><td>${rupiah(s.net_total)}</td><td><span class="badge ${s.status==='completed'?'good':s.status==='void'?'bad':'warn'}">${esc(s.status)}</span></td></tr>`).join('')}</table></div>`}
function renderSales(){ $('#pageTitle').textContent='Penjualan';$('#pageSubtitle').textContent='Riwayat transaksi toko';$('#content').innerHTML=`<div class="card"><div class="toolbar"><input id="saleSearch" placeholder="Cari invoice / kasir"><button id="exportSales" class="ghost">Export CSV</button></div><div id="salesList">${salesTable(state.sales)}</div></div>`;$('#saleSearch').oninput=()=>{const q=$('#saleSearch').value.toLowerCase();$('#salesList').innerHTML=salesTable(state.sales.filter(s=>`${s.invoice_no} ${s.profiles?.full_name} ${s.payment_method}`.toLowerCase().includes(q)))};$('#exportSales').onclick=()=>exportCSV('penjualan.csv',state.sales.map(s=>({invoice:s.invoice_no,tanggal:s.created_at,kasir:s.profiles?.full_name,metode:s.payment_method,total:s.net_total,hpp:s.cogs_total,status:s.status})))}

function renderExpenses(){ $('#pageTitle').textContent='Pengeluaran';$('#pageSubtitle').textContent='Biaya operasional mengurangi laba bersih';$('#content').innerHTML=`<div class="grid2"><div class="card"><h3>Catat Pengeluaran</h3><div class="form-grid"><label>Tanggal<input id="expDate" type="date" value="${todayISO()}"></label><label>Kategori<input id="expCategory" placeholder="Listrik, Gaji, dll"></label><label class="span2">Keterangan<input id="expDesc"></label><label>Jumlah<input id="expAmount" type="number" min="0"></label><label>Metode<select id="expMethod"><option>Tunai</option><option>Transfer</option><option>QRIS</option></select></label></div><button id="saveExpense" class="primary full">Simpan Pengeluaran</button></div><div class="card"><h3>Pengeluaran Terbaru</h3><div class="table-wrap"><table class="table"><tr><th>Tanggal</th><th>Kategori</th><th>Keterangan</th><th>Jumlah</th></tr>${state.expenses.slice(0,100).map(e=>`<tr><td>${e.expense_date}</td><td>${esc(e.category)}</td><td>${esc(e.description||'-')}</td><td>${rupiah(e.amount)}</td></tr>`).join('')}</table></div></div></div>`;$('#saveExpense').onclick=saveExpense}
async function saveExpense(){const payload={expense_date:$('#expDate').value,category:$('#expCategory').value.trim(),description:$('#expDesc').value,amount:num($('#expAmount').value),payment_method:$('#expMethod').value,created_by:state.user.id};if(!payload.category||payload.amount<=0)return toast('Lengkapi data');const{data,error}=await sb.from('expenses').insert(payload).select().single();if(error)return toast(error.message);await audit('CREATE_EXPENSE','expenses',data.id,{amount:payload.amount,category:payload.category});toast('Pengeluaran tersimpan');await refreshAll();renderExpenses()}

function renderReports(){const p=periodStats(30),inventory=state.variants.reduce((a,v)=>a+num(v.stock_qty)*num(v.products?.cost_price),0);$('#pageTitle').textContent='Laporan';$('#pageSubtitle').textContent='Penjualan, laba rugi dan stok';$('#content').innerHTML=`<div class="cards">${metric('Omzet 30 Hari',rupiah(p.omzet),'Penjualan bersih')}${metric('HPP',rupiah(p.hpp),'Harga pokok')}${metric('Laba Kotor',rupiah(p.gross),'Omzet - HPP')}${metric('Laba Bersih',rupiah(p.net),'Setelah pengeluaran',p.net>=0?'kpi-good':'kpi-bad')}</div><div class="grid2"><div class="card"><h3>Laba Rugi 30 Hari</h3><div class="stat-list"><div class="stat-row"><span>Penjualan</span><b>${rupiah(p.omzet)}</b></div><div class="stat-row"><span>Harga Pokok Penjualan</span><b>(${rupiah(p.hpp)})</b></div><div class="stat-row"><span>Laba Kotor</span><b>${rupiah(p.gross)}</b></div><div class="stat-row"><span>Pengeluaran Operasional</span><b>(${rupiah(p.exp)})</b></div><div class="stat-row"><span>Laba Bersih</span><b>${rupiah(p.net)}</b></div></div><button id="printReport" class="ghost full" style="margin-top:12px">Print Halaman</button></div><div class="card"><h3>Laporan Stok</h3><div class="stat-row"><span>Total Qty</span><b>${state.variants.reduce((a,v)=>a+num(v.stock_qty),0)} pcs</b></div><div class="stat-row"><span>Nilai Persediaan</span><b>${rupiah(inventory)}</b></div><div class="stat-row"><span>Stok Menipis</span><b>${state.variants.filter(v=>v.stock_qty<=v.min_stock).length} varian</b></div><button id="exportStock" class="ghost full" style="margin-top:12px">Export Stok CSV</button></div></div><div class="card" style="margin-top:14px"><h3>Produk & Stok</h3><div class="table-wrap"><table class="table"><tr><th>SKU</th><th>Produk</th><th>Size</th><th>Warna</th><th>Qty</th><th>Modal</th><th>Nilai</th></tr>${state.variants.map(v=>`<tr><td>${esc(v.products?.sku)}</td><td>${esc(v.products?.name)}</td><td>${esc(v.size)}</td><td>${esc(v.color)}</td><td>${v.stock_qty}</td><td>${rupiah(v.products?.cost_price)}</td><td>${rupiah(v.stock_qty*num(v.products?.cost_price))}</td></tr>`).join('')}</table></div></div>`;$('#printReport').onclick=()=>openPrintWindow('Laporan Toko',`<div style="width:100%;font-size:11px">${$('#content').innerHTML}</div>`,'report');$('#exportStock').onclick=()=>exportCSV('stok.csv',state.variants.map(v=>({sku:v.products?.sku,produk:v.products?.name,size:v.size,warna:v.color,stok:v.stock_qty,harga_modal:v.products?.cost_price,nilai:v.stock_qty*num(v.products?.cost_price)})))}
function exportCSV(filename,rows){if(!rows.length)return toast('Tidak ada data');const keys=Object.keys(rows[0]),csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(','))].join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href)}

function renderAudit(){ $('#pageTitle').textContent='Audit Log';$('#pageSubtitle').textContent='Aktivitas penting pengguna';$('#content').innerHTML=`<div class="card"><div class="table-wrap"><table class="table"><tr><th>Waktu</th><th>User</th><th>Aksi</th><th>Entitas</th><th>Detail</th></tr>${state.audit.map(a=>`<tr><td>${dateId(a.created_at)}</td><td>${esc(a.profiles?.full_name||'-')}</td><td>${esc(a.action)}</td><td>${esc(a.entity||'-')}</td><td class="audit">${esc(JSON.stringify(a.details||{}))}</td></tr>`).join('')}</table></div></div>`}
function renderSettings(){const s=state.settings;$('#pageTitle').textContent='Pengaturan Toko';$('#pageSubtitle').textContent='Identitas toko dan batas operasional';$('#content').innerHTML=`<div class="card" style="max-width:800px"><div class="form-grid"><label>Nama Toko<input id="setName" value="${esc(s.store_name||'')}"></label><label>Telepon<input id="setPhone" value="${esc(s.phone||'')}"></label><label class="span2">Alamat<textarea id="setAddress">${esc(s.address||'')}</textarea></label><label class="span2">Footer Struk<input id="setFooter" value="${esc(s.receipt_footer||'')}"></label><label>Stok Minimum Default<input id="setMin" type="number" value="${num(s.default_min_stock||3)}"></label><label>Batas Diskon Kasir (Rp)<input id="setDisc" type="number" value="${num(s.cashier_max_discount||0)}"></label></div><button id="saveSettings" class="primary full">Simpan Pengaturan</button></div>`;$('#saveSettings').onclick=saveSettings}
async function saveSettings(){const payload={store_name:$('#setName').value,address:$('#setAddress').value,phone:$('#setPhone').value,receipt_footer:$('#setFooter').value,default_min_stock:num($('#setMin').value),cashier_max_discount:num($('#setDisc').value),updated_at:new Date().toISOString()};const{error}=await sb.from('settings').update(payload).eq('id',1);if(error)return toast(error.message);await audit('UPDATE_SETTINGS','settings','1',payload);toast('Pengaturan tersimpan');await refreshAll();renderSettings()}
init();

window.addEventListener('DOMContentLoaded',()=>{const b=$('#saveProductEdit');if(b)b.onclick=saveProductEdit});
